{
 "title": "NTM - Host Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "db", "label": "Database", "query": "${VAR_DB}" },
   { "name": "rp", "label": "Retention Policy", "query": "${VAR_RP}" },
   { "name": "data_source", "label": "Data Source", "query": "influxdb" },
   {
    "name": "devicename",
    "label": "Device Name",
    "query": "show tag values from  \"$db\".\"$rp\".\"GaudiMon\" with key=host WHERE $timeFilter "
   },
   {
    "name": "min_interval",
    "query": "select last(elapsed) from (select elapsed(util,1s) from \"$db\".\"$rp\".\"GaudiMon\" where host =~ /$devicename/ and $timeFilter group by bus_id)"
   },
   { "name": "min_interval_sum", "query": "${VAR_MIN_INTERVAL_SUM}" },
   { "name": "unhealthy_hosts", "query": "gaudi-2-19,gaudi-2-37" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<table style=\"margin: 0px; padding: 0px; border: 1px; border-collapse: collapse;\" width=\"100%\">\n<tbody>\n<tr style=\"margin: 0px; padding: 0px;\">\n<td style=\"width: 15%; margin: 0px; padding: 0px; border: none;\" valign=\"middle\"><img id='cisco_logo' style=\"display: block; margin-left: auto; margin-right: auto;\" src='/public/img/ntm/cisco_logo.png' width=\"90\" />\n</td>\n<td style=\"width: 70%; margin: 0px; padding: 0px; border: none;\">\n<h2 style=\"text-align: center; margin: 2px;\"><span style=\"color: #0085FC;\"><strong>NTM - Gaudi Host Monitoring</strong></span></h2>\n</td>\n<td style=\"width: 15%; margin: 0px; border: none;\" valign=\"middle\"><img id='your_logo' style=\"display: block; margin-left: auto; margin-right: auto;\" src='/public/img/ntm/your_logo.png' alt=\"\" width=\"90\"/>\n</td>\n</tr>\n</tbody>\n</table>"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Host Inventory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "# Hosts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select count(host) from (select last(util) FROM \"GaudiMon\"  WHERE $timeFilter group by host) where $timeFilter"
    }
   ]
  },
  {
   "title": "# OAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select count(status) from (select last(status) as status FROM \"$db\".\"$rp\".\"GaudiMon\" where $timeFilter group by host,bus_id)"
    }
   ]
  },
  {
   "title": "OAM Operational Status",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 4, "y": 3 },
   "targets": [
    {
     "alias": "$col",
     "query": "select last(Disabled) as \"Disabled\" from (select count(status) as \"Disabled\" from (select last(status) as status FROM \"$db\".\"$rp\".\"GaudiMon\" where $timeFilter group by host,bus_id,time($__interval)) where status != 'Operational' group by time($__interval)) group by time($__interval)\n"
    },
    {
     "alias": "$col",
     "query": "\nselect count(status) as \"Operational\" from (select last(status) as status FROM \"$db\".\"$rp\".\"GaudiMon\" where $timeFilter group by host,bus_id,time($__interval)) where status = 'Operational' group by time($__interval)\n\n\n"
    }
   ]
  },
  {
   "title": "OAM Operational Status",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "query": "select count(status) as \"Disabled\" from (select last(status) as status FROM \"$db\".\"$rp\".\"GaudiMon\" where $timeFilter group by host,bus_id) where status != 'Operational'\n"
    },
    {
     "alias": "$col",
     "query": "\nselect count(status) as \"Operational\" from (select last(status) as status FROM \"$db\".\"$rp\".\"GaudiMon\" where $timeFilter group by host,bus_id) where status = 'Operational'\n\n\n"
    }
   ]
  },
  {
   "title": "Disabled OAMs",
   "type": "table",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select status,host,bus_id from (select last(status) as status FROM \"$db\".\"$rp\".\"GaudiMon\" where $timeFilter group by host,bus_id) where status != 'Operational'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top-10 OAMs - Utilization",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select top(util,bus_id,host,10) from (SELECT max(util) as util  FROM \"$db\".\"$rp\".\"GaudiMon\" where $timeFilter group by bus_id, host) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top-10 OAMs - Temperature",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select top(temperature,bus_id,host,10) from (SELECT max(temperature) as temperature FROM \"$db\".\"$rp\".\"GaudiMon\" where $timeFilter group by bus_id, host) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top-10 OAMs - Memory Usage",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select top(mem_used,bus_id,host,10) from (SELECT max(mem)*100/max(mem_max) as mem_used FROM \"$db\".\"$rp\".\"GaudiMon\" where $timeFilter group by bus_id, host) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top-10 OAMs - ECC",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select top(un_ecc,bus_id,host,10) from (SELECT max(un_ecc) as un_ecc FROM \"$db\".\"$rp\".\"GaudiMon\" where $timeFilter group by bus_id, host) where $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(uptime) as uptime , last(load1) as load1 FROM \"$db\".\"$rp\".\"system\"  WHERE $timeFilter group by host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(total) as total, last(used) as used, last(used)/last(total) as used_percent FROM \"$db\".\"$rp\".\"mem\"  WHERE $timeFilter group by host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) as interfaces from (select last(bytes_recv) from \"$db\".\"$rp\".\"net\"   WHERE $timeFilter group by interface,host) group by host ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(cpu_model) as cpu_model,last(driver_version) as driver_version,last(gaudi_model) as gaudi_model,last(num_cpu) as num_cpu,last(os_release) as os_release FROM \"$db\".\"$rp\".\"GaudiMon\"  WHERE $timeFilter group by host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(last) as num_hpu from (select last from (select last(util) from \"$db\".\"$rp\".\"GaudiMon\"   WHERE $timeFilter group by host,bus_id) group by host) group by host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select top(last,1) as disk_used from (SELECT last(used_percent) FROM \"autogen\".\"disk\" WHERE $timeFilter GROUP BY path,host) group by host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OAM Heatmaps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "OAM Temperature Heatmap (Celsius)",
     "type": "stat",
     "gridPos": { "h": 22, "w": 4, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_host $tag_bus_id",
       "query": "SELECT last(temperature) as temperature FROM \"$db\".\"$rp\".\"GaudiMon\" where $timeFilter group by bus_id, host"
      }
     ]
    },
    {
     "title": "OAM ECC Heatmap",
     "type": "stat",
     "gridPos": { "h": 22, "w": 5, "x": 4, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_host $tag_bus_id",
       "query": "SELECT last(un_ecc) as ecc FROM \"$db\".\"$rp\".\"GaudiMon\" where $timeFilter group by bus_id, host"
      }
     ]
    },
    {
     "title": "OAM Memory Usage Heatmap (%)",
     "type": "stat",
     "gridPos": { "h": 22, "w": 5, "x": 9, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_host $tag_bus_id",
       "query": "SELECT last(mem)*100/last(mem_max) as mem_used FROM \"$db\".\"$rp\".\"GaudiMon\" where $timeFilter group by bus_id, host"
      }
     ]
    },
    {
     "title": "OAM Utilization (%)",
     "type": "stat",
     "gridPos": { "h": 22, "w": 5, "x": 14, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_host $tag_bus_id",
       "query": "SELECT last(util) as util FROM \"$db\".\"$rp\".\"GaudiMon\" where $timeFilter group by bus_id, host"
      }
     ]
    },
    {
     "title": "OAM Power Usage (%)",
     "type": "stat",
     "gridPos": { "h": 22, "w": 5, "x": 19, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_host $tag_bus_id",
       "query": "SELECT last(pwr)*100/last(pwr_max) as pwr_used FROM \"$db\".\"$rp\".\"GaudiMon\" where $timeFilter group by bus_id, host"
      }
     ]
    }
   ]
  },
  {
   "title": "OAM External Interface Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "OAM External Interface Status",
     "type": "stat",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_intf",
       "query": "select State from (SELECT oper_state as \"State\", last(cdc) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" where \"host\" !~ /^$unhealthy_hosts$/ and $timeFilter group by host, intf) where $timeFilter group by intf,host "
      }
     ]
    },
    {
     "title": "OAM External Interface Status - $devicename",
     "type": "state-timeline",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "alias": "$tag_intf connected to $tag_peer_name ($tag_peer) $tag_peer_intf",
       "query": "select last(State) from (SELECT oper_state as \"State\", last(cdc), bus_id as \"Bus ID\"  FROM \"$db\".\"$rp\".\"GaudiExtIntf\" where \"host\" =~ /^$devicename$/ and $timeFilter and peer != '' group by host, intf, peer, peer_name, peer_intf) where $timeFilter group by time($__interval), intf, host, peer, peer_name, peer_intf"
      }
     ]
    }
   ]
  },
  {
   "title": "OAM Details of $devicename",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(clock) as clock, last(serial) as serial, last(status) as status FROM \"$db\".\"$rp\".\"GaudiMon\" where \"host\" =~ /^$devicename$/ and $timeFilter group by oam_id,bus_id",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "OAM Statistics of $devicename",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Details of $devicename",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(mem) as mem,max(mem_max) as mem_max, max(mem)*100/max(mem_max) as mem_used,max(pwr) as pwr, max(pwr_max) as pwr_max, max(pwr)*100/max(pwr_max) as pwr_used, max(temperature) as temperature, max(un_ecc) as un_ecc, max(util) as util FROM \"$db\".\"$rp\".\"GaudiMon\" where $timeFilter AND \"host\" =~ /^$devicename$/ group by oam_id,bus_id",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Power Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "alias": "OAM ID: $tag_oam_id, BUS ID: $tag_bus_id",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(pwr) FROM \"$db\".\"$rp\".\"GaudiMon\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by oam_id,bus_id,time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "targets": [
      {
       "alias": "OAM ID: $tag_oam_id, BUS ID: $tag_bus_id",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(mem) FROM \"$db\".\"$rp\".\"GaudiMon\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by oam_id,bus_id,time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "alias": "OAM ID: $tag_oam_id, BUS ID: $tag_bus_id",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(temperature) FROM \"$db\".\"$rp\".\"GaudiMon\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by oam_id,bus_id,time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Utilization",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "OAM ID: $tag_oam_id, BUS ID: $tag_bus_id",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(util) FROM \"$db\".\"$rp\".\"GaudiMon\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by oam_id,bus_id,time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Uncorrected ECC Errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "OAM ID: $tag_oam_id, BUS ID: $tag_bus_id",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(un_ecc) FROM \"$db\".\"$rp\".\"GaudiMon\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by oam_id,bus_id, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Gaudi Internal Interface Stats on $devicename",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traffic RX",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "alias": "$tag_host OAM ID: $tag_oam_id, Port: $tag_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"RX Traffic\") as \"RX Traffic\" from (SELECT non_negative_difference(OctetsReceivedOK)*8/elapsed(OctetsReceivedOK,1s) as \"RX Traffic\" FROM \"$db\".\"$rp\".\"GaudiIntIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by oam_id,bus_id,intf, host) where $timeFilter GROUP BY oam_id,bus_id,intf, host, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Traffic TX",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "alias": "$tag_host OAM ID: $tag_oam_id, Port: $tag_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"TX Traffic\") as \"TX Traffic\" from (SELECT non_negative_difference(OctetsTransmittedOK)*8/elapsed(OctetsTransmittedOK,1s) as \"TX Traffic\" FROM \"$db\".\"$rp\".\"GaudiIntIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by oam_id,bus_id,intf, host) where $timeFilter GROUP BY oam_id,bus_id,intf, host,time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Errors - pcs_local_faults, pcs_remote_faults, pcs_remote_fault_reconfig, pcs_link_restores, and aAlignmentErrors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_host OAM ID: $tag_oam_id, Port: $tag_intf - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"pcs_local_faults\" from (SELECT non_negative_difference(pcs_local_faults) FROM \"$db\".\"$rp\".\"GaudiIntIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by oam_id,bus_id,intf, host) where $timeFilter GROUP BY oam_id,bus_id,intf, host, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host OAM ID: $tag_oam_id, Port: $tag_intf - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"pcs_remote_faults\" from (SELECT non_negative_difference(pcs_remote_faults) FROM \"$db\".\"$rp\".\"GaudiIntIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by oam_id,bus_id,intf, host) where $timeFilter GROUP BY oam_id,bus_id,intf, host, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host OAM ID: $tag_oam_id, Port: $tag_intf - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"pcs_remote_fault_reconfig\" from (SELECT non_negative_difference(pcs_remote_fault_reconfig) FROM \"$db\".\"$rp\".\"GaudiIntIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by oam_id,bus_id,intf, host) where $timeFilter GROUP BY oam_id,bus_id,intf, host, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host OAM ID: $tag_oam_id, Port: $tag_intf - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"pcs_link_restores\" from (SELECT non_negative_difference(pcs_link_restores) FROM \"$db\".\"$rp\".\"GaudiIntIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by oam_id,bus_id,intf, host) where $timeFilter GROUP BY oam_id,bus_id,intf, host, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host OAM ID: $tag_oam_id, Port: $tag_intf - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"aAlignmentErrors\" from (SELECT non_negative_difference(aAlignmentErrors) FROM \"$db\".\"$rp\".\"GaudiIntIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by oam_id,bus_id,intf, host) where $timeFilter GROUP BY oam_id,bus_id,intf, host, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Errors - spmu_req_out_of_range_psn, spmu_req_unset_psn, spmu_res_duplicate_psn, and spmu_res_out_of_sequence_psn",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_host OAM ID: $tag_oam_id, Port: $tag_intf - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"spmu_req_out_of_range_psn\" from (SELECT non_negative_difference(spmu_req_out_of_range_psn) FROM \"$db\".\"$rp\".\"GaudiIntIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by oam_id,bus_id,intf,host) where $timeFilter GROUP BY oam_id,bus_id,intf,host, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host OAM ID: $tag_oam_id, Port: $tag_intf - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"spmu_req_unset_psn\" from (SELECT non_negative_difference(spmu_req_unset_psn) FROM \"$db\".\"$rp\".\"GaudiIntIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by oam_id,bus_id,intf,host) where $timeFilter GROUP BY oam_id,bus_id,intf,host, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host OAM ID: $tag_oam_id, Port: $tag_intf - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"spmu_res_duplicate_psn\" from (SELECT non_negative_difference(spmu_res_duplicate_psn) FROM \"$db\".\"$rp\".\"GaudiIntIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by oam_id,bus_id,intf,host) where $timeFilter GROUP BY oam_id,bus_id,intf,host, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host OAM ID: $tag_oam_id, Port: $tag_intf - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"spmu_res_out_of_sequence_psn\" from (SELECT non_negative_difference(spmu_res_out_of_sequence_psn) FROM \"$db\".\"$rp\".\"GaudiIntIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by oam_id,bus_id,intf,host) where $timeFilter GROUP BY oam_id,bus_id,intf,host, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Errors - aFrameTooLongErrors, aInRangeLengthErrors, aFrameCheckSequenceErrors, and ifInErrors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_host OAM ID: $tag_oam_id, Port: $tag_intf - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"aFrameTooLongErrors\" from (SELECT non_negative_difference(aFrameTooLongErrors) FROM \"$db\".\"$rp\".\"GaudiIntIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by oam_id,bus_id,intf,host) where $timeFilter GROUP BY oam_id,bus_id,intf,host, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host OAM ID: $tag_oam_id, Port: $tag_intf - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"aInRangeLengthErrors\" from (SELECT non_negative_difference(aInRangeLengthErrors) FROM \"$db\".\"$rp\".\"GaudiIntIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by oam_id,bus_id,intf,host) where $timeFilter GROUP BY oam_id,bus_id,intf,host, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host OAM ID: $tag_oam_id, Port: $tag_intf - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"aFrameCheckSequenceErrors\" from (SELECT non_negative_difference(aFrameCheckSequenceErrors) FROM \"$db\".\"$rp\".\"GaudiIntIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by oam_id,bus_id,intf,host) where $timeFilter GROUP BY oam_id,bus_id,intf,host, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host OAM ID: $tag_oam_id, Port: $tag_intf - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"ifInErrors\" from (SELECT non_negative_difference(ifInErrors) FROM \"$db\".\"$rp\".\"GaudiIntIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by oam_id,bus_id,intf,host) where $timeFilter GROUP BY oam_id,bus_id,intf,host, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Errors - Congestion_Q_err, Eth_DB_fifo_overrun",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_host OAM ID: $tag_oam_id, Port: $tag_intf - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"Congestion_Q_err\" from (SELECT non_negative_difference(Congestion_Q_err) FROM \"$db\".\"$rp\".\"GaudiIntIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by oam_id,bus_id,intf,host) where $timeFilter GROUP BY oam_id,bus_id,intf,host, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host OAM ID: $tag_oam_id, Port: $tag_intf - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"Eth_DB_fifo_overrun\" from (SELECT non_negative_difference(Eth_DB_fifo_overrun) FROM \"$db\".\"$rp\".\"GaudiIntIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by oam_id,bus_id,intf,host) where $timeFilter GROUP BY oam_id,bus_id,intf,host, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Errors - symbol_err_corrected_lane_0, 1, 2, 3",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_host OAM ID: $tag_oam_id, Port: $tag_intf - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"symbol_err_corrected_lane_0\" from (SELECT non_negative_difference(symbol_err_corrected_lane_0) FROM \"$db\".\"$rp\".\"GaudiIntIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by oam_id,bus_id,intf,host) where $timeFilter GROUP BY oam_id,bus_id,intf,host, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host OAM ID: $tag_oam_id, Port: $tag_intf - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"symbol_err_corrected_lane_1\" from (SELECT non_negative_difference(symbol_err_corrected_lane_1) FROM \"$db\".\"$rp\".\"GaudiIntIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by oam_id,bus_id,intf,host) where $timeFilter GROUP BY oam_id,bus_id,intf,host, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host OAM ID: $tag_oam_id, Port: $tag_intf - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"symbol_err_corrected_lane_2\" from (SELECT non_negative_difference(symbol_err_corrected_lane_2) FROM \"$db\".\"$rp\".\"GaudiIntIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by oam_id,bus_id,intf,host) where $timeFilter GROUP BY oam_id,bus_id,intf,host, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host OAM ID: $tag_oam_id, Port: $tag_intf - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"symbol_err_corrected_lane_3\" from (SELECT non_negative_difference(symbol_err_corrected_lane_3) FROM \"$db\".\"$rp\".\"GaudiIntIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by oam_id,bus_id,intf,host) where $timeFilter GROUP BY oam_id,bus_id,intf,host, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Errors - post_FEC_SER_exp_negative, post_FEC_SER_int, pre_FEC_SER_exp_negative, and pre_FEC_SER_int",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_host OAM ID: $tag_oam_id, Port: $tag_intf - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"post_FEC_SER_exp_negative\" from (SELECT non_negative_difference(post_FEC_SER_exp_negative) FROM \"$db\".\"$rp\".\"GaudiIntIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by oam_id,bus_id,intf,host) where $timeFilter GROUP BY oam_id,bus_id,intf,host, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host OAM ID: $tag_oam_id, Port: $tag_intf - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"post_FEC_SER_int\" from (SELECT non_negative_difference(post_FEC_SER_int) FROM \"$db\".\"$rp\".\"GaudiIntIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by oam_id,bus_id,intf,host) where $timeFilter GROUP BY oam_id,bus_id,intf,host, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host OAM ID: $tag_oam_id, Port: $tag_intf - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"pre_FEC_SER_exp_negative\" from (SELECT non_negative_difference(pre_FEC_SER_exp_negative) FROM \"$db\".\"$rp\".\"GaudiIntIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by oam_id,bus_id,intf,host) where $timeFilter GROUP BY oam_id,bus_id,intf,host, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host OAM ID: $tag_oam_id, Port: $tag_intf - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"pre_FEC_SER_int\" from (SELECT non_negative_difference(pre_FEC_SER_int) FROM \"$db\".\"$rp\".\"GaudiIntIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by oam_id,bus_id,intf,host) where $timeFilter GROUP BY oam_id,bus_id,intf,host, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Errors - cw_corrected_accum",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_host OAM ID: $tag_oam_id, Port: $tag_intf - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"cw_corrected_accum\" from (SELECT non_negative_difference(cw_corrected_accum) FROM \"$db\".\"$rp\".\"GaudiIntIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by oam_id,bus_id,intf,host) where $timeFilter GROUP BY oam_id,bus_id,intf,host, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Errors - cw_uncorrect_accum",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_host OAM ID: $tag_oam_id, Port: $tag_intf - $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"cw_uncorrect_accum\" from (SELECT non_negative_difference(cw_uncorrect_accum) FROM \"$db\".\"$rp\".\"GaudiIntIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by oam_id,bus_id,intf,host) where $timeFilter GROUP BY oam_id,bus_id,intf,host, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Gaudi External Interfaces on $devicename",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(mac) as MAC, oper_speed as \"Speed\", oper_state as \"State\",peer as \"Peer IP\",peer_type as \"Peer Type\",peer_intf as \"Peer Interface\",peer_name as \"Peer Name\"  FROM \"$db\".\"$rp\".\"GaudiExtIntf\" where \"host\" =~ /^$devicename$/ group by host,bus_id, oam_id, intf",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Gaudi External Interface Stats on $devicename",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traffic RX",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "alias": "$tag_host $tag_intf <-- $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"RX Traffic\") as \"RX Traffic\" from (SELECT non_negative_difference(OctetsReceivedOK)*8/elapsed(OctetsReceivedOK,1s) as \"RX Traffic\" FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Traffic TX",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "alias": "$tag_host $tag_intf --> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"TX Traffic\") as \"TX Traffic\" from (SELECT non_negative_difference(OctetsTransmittedOK)*8/elapsed(OctetsTransmittedOK,1s) as \"TX Traffic\" FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Pause RX",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_host $tag_intf $col <-- $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"C0\" from (SELECT non_negative_difference(aCBFCPAUSEFramesReceived_0) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col <-- $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"C1\" from (SELECT non_negative_difference(aCBFCPAUSEFramesReceived_1) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col <-- $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"C2\" from (SELECT non_negative_difference(aCBFCPAUSEFramesReceived_2) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col <-- $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"C3\" from (SELECT non_negative_difference(aCBFCPAUSEFramesReceived_3) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col <-- $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"C4\" from (SELECT non_negative_difference(aCBFCPAUSEFramesReceived_4) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col <-- $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"C5\" from (SELECT non_negative_difference(aCBFCPAUSEFramesReceived_5) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col <-- $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"C6\" from (SELECT non_negative_difference(aCBFCPAUSEFramesReceived_6) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col <-- $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"C7\" from (SELECT non_negative_difference(aCBFCPAUSEFramesReceived_7) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Pause TX",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_host $tag_intf $col --> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"C0\" from (SELECT non_negative_difference(aCBFCPAUSEFramesTransmitted_0) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col --> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"C1\" from (SELECT non_negative_difference(aCBFCPAUSEFramesTransmitted_1) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col --> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"C2\" from (SELECT non_negative_difference(aCBFCPAUSEFramesTransmitted_2) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col --> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"C3\" from (SELECT non_negative_difference(aCBFCPAUSEFramesTransmitted_3) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col --> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"C4\" from (SELECT non_negative_difference(aCBFCPAUSEFramesTransmitted_4) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col --> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"C5\" from (SELECT non_negative_difference(aCBFCPAUSEFramesTransmitted_5) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col --> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"C6\" from (SELECT non_negative_difference(aCBFCPAUSEFramesTransmitted_6) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col --> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"C7\" from (SELECT non_negative_difference(aCBFCPAUSEFramesTransmitted_7) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Errors - cw_corrected_accum",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_host $tag_intf $col <-- $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"cw_corrected_accum\" from (SELECT non_negative_difference(cw_corrected_accum) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Errors - cw_uncorrect_accum",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_host $tag_intf $col <-- $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"cw_uncorrect_accum\" from (SELECT non_negative_difference(cw_uncorrect_accum) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Errors - symbol_err_corrected_lane_0, 1, 2, 3",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_host $tag_intf $col <--> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"symbol_err_corrected_lane_0\" from (SELECT non_negative_difference(symbol_err_corrected_lane_0) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col <--> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"symbol_err_corrected_lane_1\" from (SELECT non_negative_difference(symbol_err_corrected_lane_1) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col <--> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"symbol_err_corrected_lane_2\" from (SELECT non_negative_difference(symbol_err_corrected_lane_2) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col <--> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"symbol_err_corrected_lane_3\" from (SELECT non_negative_difference(symbol_err_corrected_lane_3) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Errors - post_FEC_SER_exp_negative, post_FEC_SER_int, pre_FEC_SER_exp_negative, and pre_FEC_SER_int",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_host $tag_intf $col <--> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"post_FEC_SER_exp_negative\" from (SELECT non_negative_difference(post_FEC_SER_exp_negative) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col <--> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"post_FEC_SER_int\" from (SELECT non_negative_difference(post_FEC_SER_int) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col <--> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"pre_FEC_SER_exp_negative\" from (SELECT non_negative_difference(pre_FEC_SER_exp_negative) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col <--> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"pre_FEC_SER_int\" from (SELECT non_negative_difference(pre_FEC_SER_int) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Errors - aFrameCheckSequenceErrors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_host $tag_intf $col <-- $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"aFrameCheckSequenceErrors\" from (SELECT non_negative_difference(aFrameCheckSequenceErrors) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Errors - etherStatsJabbers, etherStatsOversizePkts, and etherStatsUndersizePkts",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_host $tag_intf $col <-- $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"etherStatsJabbers\" from (SELECT non_negative_difference(etherStatsJabbers) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col <-- $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"etherStatsOversizePkts\" from (SELECT non_negative_difference(etherStatsOversizePkts) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col <-- $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"etherStatsUndersizePkts\" from (SELECT non_negative_difference(etherStatsUndersizePkts) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Errors - bandwidth_gbps_frac, bandwidth_gbps_int, last_data_latency_usec_frac, and last_data_latency_usec_int",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_host $tag_intf $col <-- $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(bandwidth_gbps_frac) as \"bandwidth_gbps_frac\" FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col <-- $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(bandwidth_gbps_int) as \"bandwidth_gbps_int\" FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col <-- $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(last_data_latency_usec_int) as \"last_data_latency_usec_int\" FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Errors - pcs_link_restores, pcs_local_faults, pcs_remote_fault_reconfig, pcs_remote_faults, and aAlignmentErrors ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_host $tag_intf $col <--> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"pcs_link_restores\" from (SELECT non_negative_difference(pcs_link_restores) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col <--> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"pcs_local_faults\" from (SELECT non_negative_difference(pcs_local_faults) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col <--> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"pcs_remote_fault_reconfig\" from (SELECT non_negative_difference(pcs_remote_fault_reconfig) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col <--> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"pcs_remote_faults\" from (SELECT non_negative_difference(pcs_remote_faults) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col <--> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"aAlignmentErrors\" from (SELECT non_negative_difference(aAlignmentErrors) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Errors - spmu_req_out_of_range_psn, spmu_req_unset_psn, spmu_res_duplicate_psn, and spmu_res_out_of_sequence_psn",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_host $tag_intf $col <--> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"spmu_req_out_of_range_psn\" from (SELECT non_negative_difference(spmu_req_out_of_range_psn) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col <--> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"spmu_req_unset_psn\" from (SELECT non_negative_difference(spmu_req_unset_psn) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col <--> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"spmu_res_duplicate_psn\" from (SELECT non_negative_difference(spmu_res_duplicate_psn) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col <--> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"spmu_res_out_of_sequence_psn\" from (SELECT non_negative_difference(spmu_res_out_of_sequence_psn) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Errors - tx_errors, tx_dropped, rx_dropped, ifOutErrors, and ifInErrors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_host $tag_intf $col <--> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"tx_errors\" from (SELECT non_negative_difference(tx_errors) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col <--> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"tx_dropped\" from (SELECT non_negative_difference(tx_dropped) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col <--> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"rx_dropped\" from (SELECT non_negative_difference(rx_dropped) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col <--> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"ifOutErrors\" from (SELECT non_negative_difference(ifOutErrors) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col <--> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"ifInErrors\" from (SELECT non_negative_difference(ifInErrors) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Errors - Congestion_Q_err, Eth_DB_fifo_overrun, aFrameTooLongErrors, and aInRangeLengthErrors, etherStatsDropEvents, and etherStatsFragments",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_host $tag_intf $col <--> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"Congestion_Q_err\" from (SELECT non_negative_difference(Congestion_Q_err) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col <--> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"Eth_DB_fifo_overrun\" from (SELECT non_negative_difference(Eth_DB_fifo_overrun) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col <--> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"aFrameTooLongErrors\" from (SELECT non_negative_difference(aFrameTooLongErrors) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col <--> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"aInRangeLengthErrors\" from (SELECT non_negative_difference(aInRangeLengthErrors) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col <--> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"etherStatsDropEvents\" from (SELECT non_negative_difference(etherStatsDropEvents) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_host $tag_intf $col <--> $tag_peer_name $tag_peer_intf",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "select max(\"non_negative_difference\") as \"etherStatsFragments\" from (SELECT non_negative_difference(etherStatsFragments) FROM \"$db\".\"$rp\".\"GaudiExtIntf\" WHERE (\"host\" =~ /^$devicename$/) AND $timeFilter group by host,intf,peer_name,peer_intf) where $timeFilter GROUP BY host,intf,peer_name,peer_intf, time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Beta - Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "$devicename",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 18 },
     "repeat": "devicename",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_host $tag_bus_id",
       "query": "SELECT last(temperature) as temperature FROM \"$db\".\"$rp\".\"GaudiMon\" where \"host\" =~ /^$devicename$/ and $timeFilter group by bus_id, host"
      }
     ]
    }
   ]
  },
  {
   "title": "Beta - Memory Usage (%)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "$devicename",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 19 },
     "repeat": "devicename",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_host $tag_bus_id",
       "query": "SELECT last(mem)*100/last(mem_max) as mem_used FROM \"$db\".\"$rp\".\"GaudiMon\" where \"host\" =~ /^$devicename$/ and $timeFilter group by bus_id, host"
      }
     ]
    }
   ]
  },
  {
   "title": "Beta - OAM Utilization (%)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "$devicename",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 20 },
     "repeat": "devicename",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_host $tag_bus_id",
       "query": "SELECT last(util) as util FROM \"$db\".\"$rp\".\"GaudiMon\" where \"host\" =~ /^$devicename$/ and $timeFilter group by bus_id, host"
      }
     ]
    }
   ]
  }
 ]
}